// To make a music album, I need to make a list of the album covers(album covers are drawn by EEdeng from [Fe]rrats Studios™️) and ,
//  as well as a list of song titles, which were generated by an ai model called Suno at (https://suno.com/)
const songList = [
    { name: "The Apolocheese Cat", link: "the apolocheese (1).mp3" },
    { name: "Pink Penguin", link: "Pink Penguin.mp3" },
  ];
  
  let loop = false;

  const songAudio = document.querySelector("#song-audio");
  const songName = document.querySelector("song-name");


//   button controls 
// --play pause button--
const playPauseBtn = document.querySelector("play-pause-btn");
const playPauseImg = document.querySelector("play-pause-img");
playPauseBtn.addEventListener("click", togglePlay);

function playSong(no) {
    songAudio.pause();
    songAudio.src = videoList[no].link;
    songName.textContent = songList[no].name;
    songAudio.load();
    songAudio.play();

  }

  function togglePlay() {
    if(songAudio.paused|| songAudio.ended) {
        playPauseImg.src = "https://img.icons8.com/ios-glyphs/70/07421F/play--v1.png";
        songAudio.play()
    } else {
        playPauseImg.src = "https://img.icons8.com/ios-glyphs/70/07421F/pause--v1.png"
        songAudio.pause();
    }
  }