// To make a music album, I need to make a list of the album covers(album covers are drawn by EEdeng from [Fe]rrats Studios™️) and ,
//  as well as a list of song titles, which were generated by an ai model called Suno at (https://suno.com/)
const songList = [
    { name: "The Apolocheese Cat", link: "audio/the apolocheese (1).mp3" , img: "cover1.png" },
    { name: "Pink Penguin", link: "audio/Pink Penguin.mp3", img: "cover2.png" },
    { name: "Taobao Man", link: "audio/taobao man.mp3", img: "cover3.png" },
    { name: "My-estro", link: "audio/maestro.mp3", img: "cover4.jpg" },

  ];
  
  let loop = false;

  const songAudio = document.querySelector("#song-audio");
  const songName = document.querySelector("#song-name");
  const songCover = document.querySelector("#album-image")


//   button controls 
// --play pause button--
const playPauseBtn = document.querySelector("#play-pause-btn");
const playPauseImg = document.querySelector("#play-pause-img");
playPauseBtn.addEventListener("click", togglePlay);

// --volume buttons--
const volUpButton = document.querySelector("#vol-up-btn");
const volDownButton = document.querySelector("#vol-down-btn");
const muteUnmuteImg = document.querySelector("#mute-unmute-img");
const muteUnmuteButton = document.querySelector("#mute-unmute-btn");

muteUnmuteButton.addEventListener("click", toggleMute);

function toggleMute() {
    if(songAudio.muted)
        {         
            songAudio.muted=false;
            muteUnmuteImg.src = "https://img.icons8.com/ios-glyphs/40/07421F/mute--v1.png";
   
        }
        else {
            songAudio.muted=true;
            muteUnmuteImg.src = "https://img.icons8.com/ios-glyphs/40/9A155D/mute--v1.png";

        }
}


volUpButton.addEventListener("click", volumeUp);
volDownButton.addEventListener("click", volDown);

function volumeUp () {
if (songAudio.volume < 0.9) {
    songAudio.volume += 0.1;
}
}

function volDown() {
    if (songAudio.volume > 0.11) {
      songAudio.volume -= 0.1;
    }
  }
  
//   --Prev/Next Buttons--
const nextBtn = document.querySelector("#next-btn");
nextBtn.addEventListener("click", nextTrack)
const prevBtn = document.querySelector("#prev-btn");
prevBtn.addEventListener("click", prevTrack)

let currentIndex = 0;

function prevTrack() {
  console.log("previous track loading");
  currentIndex = (currentIndex - 1 + songList.length) % songList.length;
  console.log(currentIndex);
  playSongAtIndex(currentIndex);
}

function nextTrack() {
  console.log("next track loading");
  currentIndex = (currentIndex + 1) % songList.length;
  console.log(currentIndex);
  playSongAtIndex(currentIndex);
}

// Function to play video at a specific index
function playSongAtIndex(index) {
  songAudio.pause(); // Pause the video before changing source
  console.log(songList[index].link);
  songAudio.src = songList[index].link;
  songName.textContent = songList[index].name;
  songCover.src = songList[index].img;
  songAudio.load(); // Load the new source
  songAudio.play(); // Play the video
}

function playSong(no) {
    songAudio.pause();
    songAudio.src = videoList[no].link;
    songName.textContent = songList[no].name;
    songAudio.load( );
    songAudio.play();

  }

  function togglePlay() {
    if(songAudio.paused|| songAudio.ended) {
        playPauseImg.src = "https://img.icons8.com/ios-glyphs/70/07421F//pause--v1.png";
        playPauseBtn.style.backgroundColor = "#83b895";
        songAudio.play()
    } else {
        playPauseImg.src = "https://img.icons8.com/ios-glyphs/70/9A155D/play--v1.png"
        playPauseBtn.style.backgroundColor = "pink";
        songAudio.pause();
    }
  }
// --Like button--
const likeUnlikeImg = document.querySelector("#like-unlike-img");
const likeUnlikeButton = document.querySelector("#like-unlike-btn");
const likedSongs = document.querySelectorAll("#liked-songs");
const li = document.createElement("li")

likeUnlikeButton.addEventListener("click", toggleLike);

function toggleLike() {

   likedSongs.textContent = songList[no].name;

}

//   --Changing cover--
const song1Btn = document.querySelector("#song1-btn");
const song2Btn = document.querySelector("#song2-btn");
const song3Btn = document.querySelector("#song3-btn");
const song4Btn = document.querySelector("#song4-btn");

song1Btn.addEventListener("click", function playIt() {
    songAudio.pause();
    playSong(0);
  });

  song2Btn.addEventListener("click", function playIt() {
    songAudio.pause();
    playSong(1);
  });

  song3Btn.addEventListener("click", function playIt() {
    songAudio.pause();
    playSong(2);
  });

  song4Btn.addEventListener("click", function playIt() {
    songAudio.pause();
    playSong(3);
  });


function playSong(no) {
    songAudio.pause();
    songAudio.src = songList[no].link;
    songName.textContent = songList[no].name;
    songCover.src = songList[no].img;
    songAudio.load();
    songAudio.play();
  }
  

//   --progress bar--

const progressBar = document.querySelector("#progress-bar-fill");
songAudio.addEventListener("timeupdate", updateProgressBar);

function updateProgressBar() {
    const progress = (songAudio.currentTime / songAudio.duration) * 100;
        progressBar.style.width = progress + "%";
}