// To make a music album, I need to make a list of the album covers(album covers are drawn by EEdeng from [Fe]rrats Studios™️) and ,
//  as well as a list of song titles, which were generated by an ai model called Suno at (https://suno.com/)
const songList = [
    { name: "The Apolocheese Cat", link: "the apolocheese (1).mp3" },
    { name: "Pink Penguin", link: "Pink Penguin.mp3" },
  ];
  
  let loop = false;

  const songAudio = document.querySelector("#song-audio");
  

  function playSong(no) {
    myVideo.pause();
    myVideo.src = videoList[no].link;
    videoName.textContent = videoList[no].name;
    myVideo.load();
    myVideo.play();
  }